version: '3.7'
services:
  develop:
    image: node:13.10.1-alpine3.10
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: ""
    command: sh -c "cd /app && npm i && npm run develop:public"